### ISSUE TITLE
include/carve/matrix.hpp needs "#include <cstring>" header on gcc 4.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [folded/carve#3]
```
When trying to build on gcc4.4 I get this error, its easy to add myself but
would be better to add to the source.

----
/usr/lib/gcc/i686-pc-linux-gnu/4.4.0/../../../../include/c++/4.4.0/backward/back
ward_warning.h:28:2:
warning: #warning This file includes at least one deprecated or antiquated
header which may be removed without further notice at a future date. Please
use a non-deprecated interface with equivalent functionality instead. For a
listing of replacement headers and interfaces, consult the file
backward_warning.h. To disable this warning use -Wno-deprecated.
In file included from ../include/carve/geom3d.hpp:24,
                 from ../include/carve/aabb.hpp:22,
                 from aabb.cpp:22:
../include/carve/matrix.hpp: In constructor
'carve::math::Matrix3::Matrix3(double (*)[3])':
../include/carve/matrix.hpp:95: error: 'memcpy' was not declared in this scope
../include/carve/matrix.hpp: In constructor
'carve::math::Matrix3::Matrix3(double*)':
../include/carve/matrix.hpp:98: error: 'memcpy' was not declared in this scope
../include/carve/matrix.hpp: In constructor
'carve::math::Matrix::Matrix(double (*)[4])':
../include/carve/matrix.hpp:131: error: 'memcpy' was not declared in this scope
../include/carve/matrix.hpp: In constructor
'carve::math::Matrix::Matrix(double*)':
../include/carve/matrix.hpp:134: error: 'memcpy' was not declared in this scope
make[1]: *** [aabb.lo] Error 1

```

Original issue reported on code.google.com by `ideasma...@gmail.com` on 2 Jun 2009 at 1:51

**Comment by GoogleCodeExporter** [comment]
```
changes for this have been committed, will close when I get gcc4.4 installed on 
a machine for testing.
```

Original comment by `tobias.s...@gmail.com` on 2 Jun 2009 at 3:32
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Combine this with issue 4
```

Original comment by `tobias.s...@gmail.com` on 9 Jun 2009 at 1:24
- Changed state: **Duplicate**
